db.createCollection("base_datos_empleados");
db.base_datos_empleados.insertMany(
  [
  {
    "nombres": "Maria",
    "apellidos": "Garcia",
    "correo": "maria.garcia@example.com",
    "ciudad": "Madrid",
    "país": "Spain",
    "salario": 35000,
    "edad": 30,
    "altura": 165,
    "peso": 150
  },
  {
    "nombres": "John",
    "apellidos": "Smith",
    "correo": "john.smith@example.com",
    "ciudad": "New York City",
    "país": "USA",
    "salario": 40000,
    "edad": 35,
    "altura": 180,
    "peso": 180
  },
  {
    "nombres": "Emily",
    "apellidos": "Johnson",
    "correo": "emily.johnson@example.com",
    "ciudad": "Los Angeles",
    "país": "USA",
    "salario": 45000,
    "edad": 28,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Carlos",
    "apellidos": "Martinez",
    "correo": "carlos.martinez@example.com",
    "ciudad": "Buenos Aires",
    "país": "Argentina",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Laura",
    "apellidos": "Rodriguez",
    "correo": "laura.rodriguez@example.com",
    "ciudad": "Mexico City",
    "país": "Mexico",
    "salario": 32000,
    "edad": 27,
    "altura": 155,
    "peso": 140
  },
  {
    "nombres": "David",
    "apellidos": "Gonzalez",
    "correo": "david.gonzalez@example.com",
    "ciudad": "Santiago",
    "país": "Chile",
    "salario": 42000,
    "edad": 33,
    "altura": 185,
    "peso": 190
  },
  {
    "nombres": "Sofia",
    "apellidos": "Brown",
    "correo": "sofia.brown@example.com",
    "ciudad": "Chicago",
    "país": "USA",
    "salario": 37000,
    "edad": 29,
    "altura": 162,
    "peso": 135
  },
  {
    "nombres": "Michael",
    "apellidos": "Lopez",
    "correo": "michael.lopez@example.com",
    "ciudad": "Miami",
    "país": "USA",
    "salario": 48000,
    "edad": 31,
    "altura": 178,
    "peso": 175
  },
  {
    "nombres": "Ana",
    "apellidos": "Silva",
    "correo": "ana.silva@example.com",
    "ciudad": "Rio de Janeiro",
    "país": "Brazil",
    "salario": 34000,
    "edad": 26,
    "altura": 168,
    "peso": 155
  },
  {
    "nombres": "Sarah",
    "apellidos": "Wilson",
    "correo": "sarah.wilson@example.com",
    "ciudad": "Toronto",
    "país": "Canada",
    "salario": 41000,
    "edad": 34,
    "altura": 172,
    "peso": 150
  },
  {
    "nombres": "Javier",
    "apellidos": "Hernandez",
    "correo": "javier.hernandez@example.com",
    "ciudad": "Barcelona",
    "país": "Spain",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 170
  },
  {
    "nombres": "Emma",
    "apellidos": "Davis",
    "correo": "emma.davis@example.com",
    "ciudad": "Sydney",
    "país": "Australia",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Diego",
    "apellidos": "Ramirez",
    "correo": "diego.ramirez@example.com",
    "ciudad": "Lima",
    "país": "Peru",
    "salario": 36000,
    "edad": 28,
    "altura": 175,
    "peso": 160
  },
  {
    "nombres": "Jessica",
    "apellidos": "Taylor",
    "correo": "jessica.taylor@example.com",
    "ciudad": "London",
    "país": "UK",
    "salario": 47000,
    "edad": 33,
    "altura": 167,
    "peso": 140
  },
  {
    "nombres": "Pedro",
    "apellidos": "Santos",
    "correo": "pedro.santos@example.com",
    "ciudad": "Lisbon",
    "país": "Portugal",
    "salario": 35000,
    "edad": 29,
    "altura": 170,
    "peso": 155
  },
  {
    "nombres": "Rachel",
    "apellidos": "Lee",
    "correo": "rachel.lee@example.com",
    "ciudad": "Seoul",
    "país": "South Korea",
    "salario": 44000,
    "edad": 31,
    "altura": 160,
    "peso": 135
  },
  {
    "nombres": "Lucas",
    "apellidos": "Fernandez",
    "correo": "lucas.fernandez@example.com",
    "ciudad": "Buenos Aires",
    "país": "Argentina",
    "salario": 40000,
    "edad": 27,
    "altura": 175,
    "peso": 180
  },
  {
    "nombres": "Olivia",
    "apellidos": "Brown",
    "correo": "olivia.brown@example.com",
    "ciudad": "Melbourne",
    "país": "Australia",
    "salario": 46000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
 {
    "nombres": "Sophia",
    "apellidos": "Andersen",
    "correo": "sophia.andersen@example.com",
    "ciudad": "Copenhagen",
    "país": "Denmark",
    "salario": 48000,
    "edad": 29,
    "altura": 167,
    "peso": 135
  },
  {
    "nombres": "Lukas",
    "apellidos": "Schmidt",
    "correo": "lukas.schmidt@example.com",
    "ciudad": "Berlin",
    "país": "Germany",
    "salario": 43000,
    "edad": 33,
    "altura": 178,
    "peso": 170
  },
  {
    "nombres": "Alessia",
    "apellidos": "Ricci",
    "correo": "alessia.ricci@example.com",
    "ciudad": "Rome",
    "país": "Italy",
    "salario": 39000,
    "edad": 30,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Pablo",
    "apellidos": "González",
    "correo": "pablo.gonzalez@example.com",
    "ciudad": "Madrid",
    "país": "Spain",
    "salario": 42000,
    "edad": 31,
    "altura": 180,
    "peso": 170
  },
  {
    "nombres": "Emma",
    "apellidos": "Lindberg",
    "correo": "emma.lindberg@example.com",
    "ciudad": "Stockholm",
    "país": "Sweden",
    "salario": 40000,
    "edad": 27,
    "altura": 175,
    "peso": 180
  },
  {
    "nombres": "Niklas",
    "apellidos": "Andersson",
    "correo": "niklas.andersson@example.com",
    "ciudad": "Oslo",
    "país": "Norway",
    "salario": 45000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Laura",
    "apellidos": "Martínez",
    "correo": "laura.martinez@example.com",
    "ciudad": "Barcelona",
    "país": "Spain",
    "salario": 37000,
    "edad": 29,
    "altura": 162,
    "peso": 135
  },
  {
    "nombres": "Liam",
    "apellidos": "Smith",
    "correo": "liam.smith@example.com",
    "ciudad": "London",
    "país": "UK",
    "salario": 46000,
    "edad": 31,
    "altura": 167,
    "peso": 140
  },
  {
    "nombres": "Hanna",
    "apellidos": "Nielsen",
    "correo": "hanna.nielsen@example.com",
    "ciudad": "Copenhagen",
    "país": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Maximilian",
    "apellidos": "Müller",
    "correo": "maximilian.muller@example.com",
    "ciudad": "Berlin",
    "país": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Giulia",
    "apellidos": "Rossi",
    "correo": "giulia.rossi@example.com",
    "ciudad": "Rome",
    "país": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Santiago",
    "apellidos": "López",
    "correo": "santiago.lopez@example.com",
    "ciudad": "Madrid",
    "país": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Elsa",
    "apellidos": "Andersson",
    "correo": "elsa.andersson@example.com",
    "ciudad": "Stockholm",
    "país": "Sweden",
    "salario": 40000,
    "edad": 27,
    "altura": 175,
    "peso": 180
  },
  {
    "nombres": "Oskar",
    "apellidos": "Berg",
    "correo": "oskar.berg@example.com",
    "ciudad": "Oslo",
    "país": "Norway",
    "salario": 45000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Elena",
    "apellidos": "García",
    "correo": "elena.garcia@example.com",
    "ciudad": "Barcelona",
    "país": "Spain",
    "salario": 37000,
    "edad": 29,
    "altura": 162,
    "peso": 135
  },
  {
    "nombres": "James",
    "apellidos": "Johnson",
    "correo": "james.johnson@example.com",
    "ciudad": "London",
    "país": "UK",
    "salario": 46000,
    "edad": 31,
    "altura": 167,
    "peso": 140
  },
  {
    "nombres": "Freja",
    "apellidos": "Nielsen",
    "correo": "freja.nielsen@example.com",
    "ciudad": "Copenhagen",
    "país": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Lukas",
    "apellidos": "Schneider",
    "correo": "lukas.schneider@example.com",
    "ciudad": "Berlin",
    "país": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Chiara",
    "apellidos": "Russo",
    "correo": "chiara.russo@example.com",
    "ciudad": "Rome",
    "país": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Mateo",
    "apellidos": "Gómez",
    "correo": "mateo.gomez@example.com",
    "ciudad": "Madrid",
    "país": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Filippa",
    "apellidos": "Andersson",
    "correo": "filippa.andersson@example.com",
    "ciudad": "Stockholm",
    "país": "Sweden",
    "salario": 40000,
    "edad": 27,
    "altura": 175,
    "peso": 180
  },
  {
    "nombres": "Marius",
    "apellidos": "Berg",
    "correo": "marius.berg@example.com",
    "ciudad": "Oslo",
    "país": "Norway",
    "salario": 45000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Sara",
    "apellidos": "García",
    "correo": "sara.garcia@example.com",
    "ciudad": "Barcelona",
    "país": "Spain",
    "salario": 37000,
    "edad": 29,
    "altura": 162,
    "peso": 135
  },
  {
    "nombres": "Jack",
    "apellidos": "Johnson",
    "correo": "jack.johnson@example.com",
    "ciudad": "London",
    "país": "UK",
    "salario": 46000,
    "edad": 31,
    "altura": 167,
    "peso": 140
  },
  {
    "nombres": "Viggo",
    "apellidos": "Nielsen",
    "correo": "viggo.nielsen@example.com",
    "ciudad": "Copenhagen",
    "país": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Finn",
    "apellidos": "Schulz",
    "correo": "finn.schulz@example.com",
    "ciudad": "Berlin",
    "país": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Chiara",
    "apellidos": "Romano",
    "correo": "chiara.romano@example.com",
    "ciudad": "Rome",
    "país": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Ismael",
    "apellidos": "Gutiérrez",
    "correo": "ismael.gutierrez@example.com",
    "ciudad": "Madrid",
    "país": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Alice",
    "apellidos": "Johansson",
    "correo": "alice.johansson@example.com",
    "ciudad": "Stockholm",
    "país": "Sweden",
    "salario": 40000,
    "edad": 27,
    "altura": 175,
    "peso": 180
  },
  {
    "nombres": "Oscar",
    "apellidos": "Berg",
    "correo": "oscar.berg@example.com",
    "ciudad": "Oslo",
    "país": "Norway",
    "salario": 45000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Elena",
    "apellidos": "García",
    "correo": "elena.garcia@example.com",
    "ciudad": "Barcelona",
    "país": "Spain",
    "salario": 37000,
    "edad": 29,
    "altura": 162,
    "peso": 135
  },
  {
    "nombres": "Noah",
    "apellidos": "Jensen",
    "correo": "noah.jensen@example.com",
    "ciudad": "Copenhagen",
    "país": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Paul",
    "apellidos": "Schneider",
    "correo": "paul.schneider@example.com",
    "ciudad": "Berlin",
    "país": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Lorenzo",
    "apellidos": "Ricci",
    "correo": "lorenzo.ricci@example.com",
    "ciudad": "Rome",
    "país": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Marta",
    "apellidos": "Gómez",
    "correo": "marta.gomez@example.com",
    "ciudad": "Madrid",
    "país": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Oliver",
    "apellidos": "Johansson",
    "correo": "oliver.johansson@example.com",
    "ciudad": "Stockholm",
    "país": "Sweden",
    "salario": 40000,
    "edad": 27,
    "altura": 175,
    "peso": 180
  },
  {
    "nombres": "Liam",
    "apellidos": "Berg",
    "correo": "liam.berg@example.com",
    "ciudad": "Oslo",
    "país": "Norway",
    "salario": 45000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Lucía",
    "apellidos": "García",
    "correo": "lucia.garcia@example.com",
    "ciudad": "Barcelona",
    "país": "Spain",
    "salario": 37000,
    "edad": 29,
    "altura": 162,
    "peso": 135
  },
  {
    "nombres": "Harry",
    "apellidos": "Johnson",
    "correo": "harry.johnson@example.com",
    "ciudad": "London",
    "país": "UK",
    "salario": 46000,
    "edad": 31,
    "altura": 167,
    "peso": 140
  },
  {
    "nombres": "Mathilde",
    "apellidos": "Nielsen",
    "correo": "mathilde.nielsen@example.com",
    "ciudad": "Copenhagen",
    "país": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Lorenzo",
    "apellidos": "Romano",
    "correo": "lorenzo.romano@example.com",
    "ciudad": "Rome",
    "país": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Elena",
    "apellidos": "Gutiérrez",
    "correo": "elena.gutierrez@example.com",
    "ciudad": "Madrid",
    "país": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Alice",
    "apellidos": "Jensen",
    "correo": "alice.jensen@example.com",
    "ciudad": "Copenhagen",
    "país": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Oscar",
    "apellidos": "Schneider",
    "correo": "oscar.schneider@example.com",
    "ciudad": "Berlin",
    "país": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Oliver",
    "apellidos": "Ricci",
    "correo": "oliver.ricci@example.com",
    "ciudad": "Rome",
    "país": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Lucas",
    "apellidos": "Gómez",
    "correo": "lucas.gomez@example.com",
    "ciudad": "Madrid",
    "país": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Emma",
    "apellidos": "Johansson",
    "correo": "emma.johansson@example.com",
    "ciudad": "Stockholm",
    "país": "Sweden",
    "salario": 40000,
    "edad": 27,
    "altura": 175,
    "peso": 180
  },
  {
    "nombres": "Marius",
    "apellidos": "Berg",
    "correo": "marius.berg@example.com",
    "ciudad": "Oslo",
    "país": "Norway",
    "salario": 45000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Sara",
    "apellidos": "García",
    "correo": "sara.garcia@example.com",
    "ciudad": "Barcelona",
    "país": "Spain",
    "salario": 37000,
    "edad": 29,
    "altura": 162,
    "peso": 135
  },
  {
    "nombres": "Jack",
    "apellidos": "Johnson",
    "correo": "jack.johnson@example.com",
    "ciudad": "London",
    "país": "UK",
    "salario": 46000,
    "edad": 31,
    "altura": 167,
    "peso": 140
  },
  {
    "nombres": "Viggo",
    "apellidos": "Nielsen",
    "correo": "viggo.nielsen@example.com",
    "ciudad": "Copenhagen",
    "país": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Finn",
    "apellidos": "Schulz",
    "correo": "finn.schulz@example.com",
    "ciudad": "Berlin",
    "país": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Chiara",
    "apellidos": "Romano",
    "correo": "chiara.romano@example.com",
    "ciudad": "Rome",
    "país": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Ismael",
    "apellidos": "Gutiérrez",
    "correo": "ismael.gutierrez@example.com",
    "ciudad": "Madrid",
    "país": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Alice",
    "apellidos": "Johansson",
    "correo": "alice.johansson@example.com",
    "ciudad": "Stockholm",
    "país": "Sweden",
    "salario": 40000,
    "edad": 27,
    "altura": 175,
    "peso": 180
  },
  {
    "nombres": "Oscar",
    "apellidos": "Berg",
    "correo": "oscar.berg@example.com",
    "ciudad": "Oslo",
    "país": "Norway",
    "salario": 45000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Elena",
    "apellidos": "García",
    "correo": "elena.garcia@example.com",
    "ciudad": "Barcelona",
    "país": "Spain",
    "salario": 37000,
    "edad": 29,
    "altura": 162,
    "peso": 135
  },
  {
    "nombres": "James",
    "apellidos": "Johnson",
    "correo": "james.johnson@example.com",
    "ciudad": "London",
    "país": "UK",
    "salario": 46000,
    "edad": 31,
    "altura": 167,
    "peso": 140
  },
    {
    "nombres": "Emma",
    "apellidos": "Schneider",
    "correo": "emma.schneider@example.com",
    "ciudad": "Berlin",
    "país": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Matteo",
    "apellidos": "Romano",
    "correo": "matteo.romano@example.com",
    "ciudad": "Rome",
    "país": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Lucía",
    "apellidos": "Gutiérrez",
    "correo": "lucia.gutierrez@example.com",
    "ciudad": "Madrid",
    "país": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Oscar",
    "apellidos": "Jensen",
    "correo": "oscar.jensen@example.com",
    "ciudad": "Copenhagen",
    "país": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Lena",
    "apellidos": "Schulz",
    "correo": "lena.schulz@example.com",
    "ciudad": "Berlin",
    "país": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Alessandro",
    "apellidos": "Moretti",
    "correo": "alessandro.moretti@example.com",
    "ciudad": "Rome",
    "país": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Sara",
    "apellidos": "Gómez",
    "correo": "sara.gomez@example.com",
    "ciudad": "Madrid",
    "país": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Oliver",
    "apellidos": "Johannessen",
    "correo": "oliver.johannessen@example.com",
    "ciudad": "Oslo",
    "país": "Norway",
    "salario": 45000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Hannah",
    "apellidos": "Andersen",
    "correo": "hannah.andersen@example.com",
    "ciudad": "Copenhagen",
    "país": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Mika",
    "apellidos": "Schulz",
    "correo": "mika.schulz@example.com",
    "ciudad": "Berlin",
    "país": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Elisa",
    "apellidos": "Bianchi",
    "correo": "elisa.bianchi@example.com",
    "ciudad": "Rome",
    "país": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Carlos",
    "apellidos": "Hernández",
    "correo": "carlos.hernandez@example.com",
    "ciudad": "Madrid",
    "país": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Freja",
    "apellidos": "Jensen",
    "correo": "freja.jensen@example.com",
    "ciudad": "Copenhagen",
    "país": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Finn",
    "apellidos": "Meyer",
    "correo": "finn.meyer@example.com",
    "ciudad": "Berlin",
    "país": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Giulia",
    "apellidos": "Conti",
    "correo": "giulia.conti@example.com",
    "ciudad": "Rome",
    "país": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Alejandro",
    "apellidos": "Sánchez",
    "correo": "alejandro.sanchez@example.com",
    "ciudad": "Madrid",
    "país": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Ella",
    "apellidos": "Larsen",
    "correo": "ella.larsen@example.com",
    "ciudad": "Copenhagen",
    "país": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Leon",
    "apellidos": "Hoffmann",
    "correo": "leon.hoffmann@example.com",
    "ciudad": "Berlin",
    "país": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Giorgia",
    "apellidos": "Rizzo",
    "correo": "giorgia.rizzo@example.com",
    "ciudad": "Rome",
    "país": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Hugo",
    "apellidos": "Fernández",
    "correo": "hugo.fernandez@example.com",
    "ciudad": "Madrid",
    "país": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Nora",
    "apellidos": "Christensen",
    "correo": "nora.christensen@example.com",
    "ciudad": "Copenhagen",
    "país": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Felix",
    "apellidos": "Lehmann",
    "correo": "felix.lehmann@example.com",
    "ciudad": "Berlin",
    "país": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Alessia",
    "apellidos": "Martini",
    "correo": "alessia.martini@example.com",
    "ciudad": "Rome",
    "país": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Javier",
    "apellidos": "Gómez",
    "correo": "javier.gomez@example.com",
    "ciudad": "Madrid",
    "país": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Malou",
    "apellidos": "Petersen",
    "correo": "malou.petersen@example.com",
    "ciudad": "Copenhagen",
    "país": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Friedrich",
    "apellidos": "Schmidt",
    "correo": "friedrich.schmidt@example.com",
    "ciudad": "Berlin",
    "país": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Caterina",
    "apellidos": "De Angelis",
    "correo": "caterina.deangelis@example.com",
    "ciudad": "Rome",
    "país": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Marcos",
    "apellidos": "Martínez",
    "correo": "marcos.martinez@example.com",
    "ciudad": "Madrid",
    "país": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Sophie",
    "apellidos": "Larsen",
    "correo": "sophie.larsen@example.com",
    "ciudad": "Copenhagen",
    "país": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Leon",
    "apellidos": "Hoffmann",
    "correo": "leon.hoffmann@example.com",
    "ciudad": "Berlin",
    "país": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Giorgia",
    "apellidos": "Rizzo",
    "correo": "giorgia.rizzo@example.com",
    "ciudad": "Rome",
    "país": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Hugo",
    "apellidos": "Fernández",
    "correo": "hugo.fernandez@example.com",
    "ciudad": "Madrid",
    "país": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Nora",
    "apellidos": "Christensen",
    "correo": "nora.christensen@example.com",
    "ciudad": "Copenhagen",
    "país": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
    {
    "nombres": "Sophia",
    "apellidos": "Andersen",
    "correo": "sophia.andersen@example.com",
    "ciudad": "Copenhagen",
    "país": "Denmark",
    "salario": 48000,
    "edad": 29,
    "altura": 167,
    "peso": 135
  },
  {
    "nombres": "Lukas",
    "apellidos": "Schmidt",
    "correo": "lukas.schmidt@example.com",
    "ciudad": "Berlin",
    "país": "Germany",
    "salario": 43000,
    "edad": 33,
    "altura": 178,
    "peso": 170
  },
  {
    "nombres": "Alessia",
    "apellidos": "Ricci",
    "correo": "alessia.ricci@example.com",
    "ciudad": "Rome",
    "país": "Italy",
    "salario": 39000,
    "edad": 30,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Pablo",
    "apellidos": "González",
    "correo": "pablo.gonzalez@example.com",
    "ciudad": "Madrid",
    "país": "Spain",
    "salario": 42000,
    "edad": 31,
    "altura": 180,
    "peso": 170
  },
  {
    "nombres": "Emma",
    "apellidos": "Lindberg",
    "correo": "emma.lindberg@example.com",
    "ciudad": "Stockholm",
    "país": "Sweden",
    "salario": 40000,
    "edad": 27,
    "altura": 175,
    "peso": 180
  },
  {
    "nombres": "Niklas",
    "apellidos": "Andersson",
    "correo": "niklas.andersson@example.com",
    "ciudad": "Oslo",
    "país": "Norway",
    "salario": 45000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Laura",
    "apellidos": "Martínez",
    "correo": "laura.martinez@example.com",
    "ciudad": "Barcelona",
    "país": "Spain",
    "salario": 37000,
    "edad": 29,
    "altura": 162,
    "peso": 135
  },
  {
    "nombres": "Liam",
    "apellidos": "Smith",
    "correo": "liam.smith@example.com",
    "ciudad": "London",
    "país": "UK",
    "salario": 46000,
    "edad": 31,
    "altura": 167,
    "peso": 140
  },
  {
    "nombres": "Hanna",
    "apellidos": "Nielsen",
    "correo": "hanna.nielsen@example.com",
    "ciudad": "Copenhagen",
    "país": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Maximilian",
    "apellidos": "Müller",
    "correo": "maximilian.muller@example.com",
    "ciudad": "Berlin",
    "país": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  },
  {
    "nombres": "Giulia",
    "apellidos": "Rossi",
    "correo": "giulia.rossi@example.com",
    "ciudad": "Rome",
    "país": "Italy",
    "salario": 42000,
    "edad": 31,
    "altura": 160,
    "peso": 130
  },
  {
    "nombres": "Santiago",
    "apellidos": "López",
    "correo": "santiago.lopez@example.com",
    "ciudad": "Madrid",
    "país": "Spain",
    "salario": 38000,
    "edad": 32,
    "altura": 175,
    "peso": 170
  },
  {
    "nombres": "Elsa",
    "apellidos": "Andersson",
    "correo": "elsa.andersson@example.com",
    "ciudad": "Stockholm",
    "país": "Sweden",
    "salario": 40000,
    "edad": 27,
    "altura": 175,
    "peso": 180
  },
  {
    "nombres": "Oskar",
    "apellidos": "Berg",
    "correo": "oskar.berg@example.com",
    "ciudad": "Oslo",
    "país": "Norway",
    "salario": 45000,
    "edad": 30,
    "altura": 165,
    "peso": 145
  },
  {
    "nombres": "Elena",
    "apellidos": "García",
    "correo": "elena.garcia@example.com",
    "ciudad": "Barcelona",
    "país": "Spain",
    "salario": 37000,
    "edad": 29,
    "altura": 162,
    "peso": 135
  },
  {
    "nombres": "James",
    "apellidos": "Johnson",
    "correo": "james.johnson@example.com",
    "ciudad": "London",
    "país": "UK",
    "salario": 46000,
    "edad": 31,
    "altura": 167,
    "peso": 140
  },
  {
    "nombres": "Freja",
    "apellidos": "Nielsen",
    "correo": "freja.nielsen@example.com",
    "ciudad": "Copenhagen",
    "país": "Denmark",
    "salario": 43000,
    "edad": 32,
    "altura": 163,
    "peso": 125
  },
  {
    "nombres": "Lukas",
    "apellidos": "Schneider",
    "correo": "lukas.schneider@example.com",
    "ciudad": "Berlin",
    "país": "Germany",
    "salario": 39000,
    "edad": 30,
    "altura": 180,
    "peso": 175
  }
  ]
)

db.base_datos_empleados.deleteMany({});
db.base_datos_empleados.find({nombres: {$eq: "Juan"}})